{% set name = "allure-python-commons" %}
{% set version = "2.8.33" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a008bb4fc4d21ed6a9e316fac2bc913bae9edb48963f703969ac2ddd0f220e99

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
    - setuptools
    - setuptools_scm
  run:
    - attrs >=16.0.0
    - pluggy >=0.4.0
    - python >=3.4
    - six >=1.9.0

test:
  imports:
    - allure
    - allure_commons

about:
  home: https://github.com/allure-framework/allure-python
  license: Apache-2.0
  license_file: LICENSE
  summary: Common module for integrate allure with python-based frameworks

extra:
  recipe-maintainers:
    - nsoranzo
